# Generated by Django 4.2.10 on 2025-02-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_attribute_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
