# Generated by Django 4.2.10 on 2025-02-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
