# Generated by Django 4.2.10 on 2025-02-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_image_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
