# Generated by Django 4.2.10 on 2025-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/products/default.jfif', upload_to='images/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
