# Generated by Django 4.2.10 on 2025-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/multiple/%Y/%m/%d', verbose_name='Фото товару'),
        ),
    ]
