# Generated by Django 4.2.10 on 2025-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products/products/default.jfif', upload_to='images/products/multiple/%Y/%m/%d', verbose_name='Фото товару'),
        ),
    ]
