# Generated by Django 4.2.10 on 2025-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/products/default.jfif', upload_to='images/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
