# Generated by Django 4.2.10 on 2025-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Код товару'),
        ),
    ]
