# Generated by Django 4.2.10 on 2025-03-07 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_price_alter_product_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Код товару'),
        ),
    ]
