"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import environ
from django.contrib import messages


BASE_DIR = Path(__file__).resolve().parent.parent
ENV_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
env.read_env(ENV_DIR / '.env')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o!66*o(mj#%z!d+1ouqf*476jgxk7yy^5c1a3l94*72-!4wo(s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Дозвіл для всіх джерел (НЕБЕЗПЕЧНО у продакшені):
CORS_ALLOW_ALL_ORIGINS = True
# Якщо ваш запит вимагає облікових даних (наприклад, cookie або токен), додайте:
#CORS_ALLOW_CREDENTIALS = True
# Якщо ваші запити використовують кастомні заголовки:
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "Access-Control-Allow-Origin",
    "X-CSRFToken",  # ✅ Додаємо CSRF-токен у дозволені заголовки
    # Інші заголовки, якщо потрібно
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party libraries
    'mathfilters',
    'crispy_forms',
    "crispy_bootstrap5",
    'django_email_verification',
    'django_google_fonts',
    'django_celery_beat',
    'django_celery_results',
    'sorl.thumbnail',
    "django_htmx",
    ##'rest_framework',
    'djoser',
    'drf_yasg',
    # Apps
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'account.apps.AccountConfig',
    'payment.apps.PaymentConfig',
    'recommend.apps.RecommendConfig',
    'api.apps.ApiConfig',
    # CORS
    ##"corsheaders",

    ##'rest_framework_simplejwt',
    'eski',
    'django_cleanup.apps.CleanupConfig',
    'django_filters',


    # Security apps
    "axes",  # Brute-force protection
    "auditlog",  # Logging user actions
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Додайте першим
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "axes.middleware.AxesMiddleware",  # Brute-force protection

]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'project' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.template.context_processors.settings', # this is new
                
                # Custom Context Processors
                'shop.context_processors.categories',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT", default=5432),
    }
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# Project Inside Settings
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# Static Files 
'''
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /'static'
STATICFILES_DIRS = [
    BASE_DIR / 'project' / 'static',
]

MEDIA_URL ='/media/'
MEDIA_ROOT = BASE_DIR /'media'
'''
import os
STATIC_URL = '/static/'
#STATIC_ROOT = os.getenv("APP_PATH_STATIC", BASE_DIR / 'static')
STATIC_ROOT = '/app/static/'  # ✅ Вірний шлях у контейнері

MEDIA_URL = '/media/'
#MEDIA_ROOT = os.getenv("APP_PATH_MEDIA", BASE_DIR / 'media')
MEDIA_ROOT = '/app/media/'  # ✅ Шлях до медіа в контейнері

STATICFILES_DIRS = [
    BASE_DIR / 'project' / 'static',  # Додайте лише якщо у вас є додаткові статичні файли
]

# Django Message
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
 }


# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


def email_verified_callback(user):
    user.is_active = True

#def password_change_callback(user, password):
#    user.set_password(password)


# Global Package Settings
EMAIL_FROM_ADDRESS = env('EMAIL_HOST_SENDER')  # mandatory
EMAIL_PAGE_DOMAIN = 'http://127.0.0.1:8000/'  # mandatory (unless you use a custom link)
EMAIL_MULTI_USER = False  # optional (defaults to False)

# Email Verification Settings (mandatory for email sending)
EMAIL_MAIL_SUBJECT = 'Confirm your email {{ user.username }}'
EMAIL_MAIL_HTML = 'account/email/mail_body.html'
EMAIL_MAIL_PLAIN = 'account/email/mail_body.txt'
EMAIL_MAIL_TOKEN_LIFE = 60 * 60  # one hour

# Email Verification Settings (mandatory for builtin view)
EMAIL_MAIL_PAGE_TEMPLATE = 'account/email/email_success_template.html'
EMAIL_MAIL_CALLBACK = email_verified_callback

# Password Recovery Settings (mandatory for email sending)
#EMAIL_PASSWORD_SUBJECT = 'Change your password {{ user.username }}'
#EMAIL_PASSWORD_HTML = 'password_body.html'
#EMAIL_PASSWORD_PLAIN = 'password_body.txt'
#EMAIL_PASSWORD_TOKEN_LIFE = 60 * 10  # 10 minutes

# Password Recovery Settings (mandatory for builtin view)
#EMAIL_PASSWORD_PAGE_TEMPLATE = 'password_changed_template.html'
#EMAIL_PASSWORD_CHANGE_PAGE_TEMPLATE = 'password_change_template.html'
#EMAIL_PASSWORD_CALLBACK = password_change_callback

# For Django Email Backend
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_SENDER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_APP_PASSWORD')  # os.environ['password_key'] suggested
EMAIL_USE_TLS = True


# Stripe
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_API_VERSION = env('STRIPE_API_VERSION')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET')

# Yookassa
YOOKASSA_SECRET_KEY = env('YOOKASSA_SECRET_KEY')
YOOKASSA_SHOP_ID = env('YOOKASSA_SHOP_ID')


# Google Fonts
# FIXME: django_google_fonts: Failed to get font: Montserrat:wght@300,400,500, got status code: 400
# GOOGLE_FONTS = ['Montserrat:wght@300,400,500', 'Roboto']
GOOGLE_FONTS = ['Montserrat:wght@300;400;500', 'Roboto']
GOOGLE_FONTS_DIR = BASE_DIR / 'static'


# TODO: add celery flower monitoring panel to docker-compose
# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_RESULT_EXTENDED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# CELERY_BEAT_SCHEDULE = {
#     "sample_task": {
#         "task": "core.tasks.sample_task",
#         "schedule": crontab(minute="*/1"),
#     },
# }


# Django REST framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        "rest_framework.authentication.SessionAuthentication",  # 🔥 HttpOnly cookies
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "api.permissions.IsAdminOrReadOnly",
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        #'rest_framework.throttling.AnonRateThrottle',
        #'rest_framework.throttling.UserRateThrottle',
        #'api.throttles.AdminRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '6/minute',
        'user': '20/minute',
        'admin': '40/minute',
    },
    
    "DEFAULT_PAGINATION_CLASS": "api.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 15,
    #'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    #'PAGE_SIZE': 15,  # Ліміт записів на сторінку
    # сортування для всього
    #'ORDERING_PARAM': 'ordering',
    #'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    #'DEFAULT_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',  # <--- ДОДАНО
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',  # Додай, якщо немає
}

'''
# Authentication
SIMPLE_JWT = {
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    #'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=3000),#######################################################################################################
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}
'''
'''
DJOSER = {
    "LOGIN_FIELD": "email",
    "SERIALIZERS": {
        "user_create": "api.serializers.CustomUserCreateSerializer",
        "user": "api.serializers.DjoserCustomUserSerializer",  # Додаємо сюди кастомний user
    },
    'AUTH_HEADER_TYPES': ('JWT',),
}
'''
DJOSER = {
    #"LOGIN_FIELD": "email",
    "LOGIN_FIELD": "username",
    "USER_CREATE_PASSWORD_RETYPE": True,
    "SEND_ACTIVATION_EMAIL": False,
    "SERIALIZERS": {
        "user_create": "djoser.serializers.UserCreateSerializer",
        "user": "djoser.serializers.UserSerializer",
        "current_user": "account.serializers.CustomUserSerializer",  # Оновлюємо /users/me/
    },
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'log' / 'django.log',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
'''
DJANGO_FILTERS_CONFIG = {
    'DISABLE_TEMPLATE_RENDERING': True
}
'''

AUTH_USER_MODEL = 'account.CustomUser'
'''
SWAGGER_SETTINGS = {
    'DEFAULT_FIELD_INSPECTORS': [
        #'drf_yasg.inspectors.SwaggerAutoSchema',
        'drf_yasg.inspectors.CamelCaseJSONFilter',
        'drf_yasg.inspectors.base.FieldInspector',  # стандартний інспектор
        'api.swagger_inspectors.CustomFieldInspector',  # наш кастомний інспектор
        'drf_yasg.inspectors.FileFieldInspector',
        'drf_yasg.inspectors.SimpleFieldInspector',
        'drf_yasg.inspectors.StringDefaultFieldInspector',
    ],
}
'''
'''
SWAGGER_SETTINGS = {
    #'DEFAULT_AUTO_SCHEMA_CLASS': 'api.schema.CustomAutoSchema',
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}
'''
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,  # ✅ Вимикає потребу логіну для Swagger
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
        }
    },
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

# Налаштування сесій через HttpOnly
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Використовуємо БД для збереження сесій
#SESSION_COOKIE_HTTPONLY = False  # Захист від доступу JavaScript                                     # Вимикає HttpOnly для сесійних cookies     True
#SESSION_COOKIE_SECURE = False  # Увімкнути лише у HTTPS (для локального сервера False)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Закривається разом із браузером


# Налаштування CORS
CORS_ALLOW_CREDENTIALS = True
'''
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Для React/Vue
    "http://127.0.0.1:3000",
]
'''
#CORS_ALLOWED_ORIGINS = ['*']

#CSRF_COOKIE_HTTPONLY = False                                    # Вимикає HttpOnly     True
#CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]
#CSRF_TRUSTED_ORIGINS = ['*']




CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # ✅ Дозволь запити з фронтенду Vue 3
    "http://127.0.0.1:5173",
    "http://192.168.163.10:5173",  # ✅ Додай правильний формат
    "http://172.16.100.3",
    "http://127.0.0.1:3000",
    "https://yourdomain.com"
]





# Cookies & CSRF
SESSION_COOKIE_HTTPONLY = True # Запобігає доступу через JavaScript
SESSION_COOKIE_SECURE = False # Використовувати лише HTTPS   # Увімкнути лише у HTTPS (для локального сервера False)
SESSION_COOKIE_SAMESITE = "Strict" # Запобігає CSRF-атакам
##SESSION_COOKIE_SAMESITE = "None"  # ✅ Дозволяє передачу через `credentials: "include"`
CSRF_COOKIE_HTTPONLY = True # Запобігає доступу до CSRF-токена через JS         ##################################  True ##################################
CSRF_COOKIE_SECURE = False # Використовувати лише HTTPS                         ################################## Для локального сервера, у продакшені ставимо True
#CSRF_COOKIE_SAMESITE = "Strict" # Посилений захист від CSRF
##CSRF_COOKIE_SAMESITE = "None"  # ✅ Дозволяє використання у міжсайтовому контексті
#CSRF_TRUSTED_ORIGINS = ["https://yourshop.com"]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # ✅ Додаємо фронтенд як довірену зону
    "http://127.0.0.1:5173",
    "http://192.168.163.10:8000",
    "http://192.168.163.10:5173",   # 🔹 Додай схему HTTP
    "http://127.0.0.1:3000",   # 🔹 Локальний хост
    "https://yourdomain.com"   # 🔹 Додай production-домен (якщо є)
    
]
CSRF_COOKIE_NAME = "csrftoken"


# HTTP security
SECURE_BROWSER_XSS_FILTER = True # Захист від XSS
SECURE_CONTENT_TYPE_NOSNIFF = True # Захист від Content-Type sniffing
X_FRAME_OPTIONS = "DENY" # Захист від clickjacking
SECURE_SSL_REDIRECT = False # Примусове перенаправлення на HTTPS               ##################################  True ##################################
SECURE_HSTS_SECONDS = 31536000 # Увімкнення HSTS (1 рік)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Django Axes
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1 # Блокування на 1 годину
AXES_LOCKOUT_TEMPLATE = "errors/lockout.html"

# SimpleJWT (Токени в HttpOnly cookies)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    'UPDATE_LAST_LOGIN': True,
}

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # ✅ Правильний бекенд для django-axes 5.0+
    "django.contrib.auth.backends.ModelBackend",  # ✅ Стандартний бекенд Django
]