# Generated by Django 4.2.10 on 2025-02-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eski', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
