# Generated by Django 4.2.10 on 2025-02-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eski', '0005_alter_customuser_language_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
