# Generated by Django 4.2.10 on 2025-02-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eski', '0006_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва атрибуту', max_length=255, unique=True)),
                ('value', models.CharField(blank=True, help_text="Значення атрибуту (необов'язково)", max_length=255, null=True)),
            ],
        ),
    ]
