# Generated by Django 4.2.10 on 2025-02-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eski', '0007_attribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
