# Generated by Django 4.2.10 on 2025-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('courier', 'Кур’єр'), ('pickup', 'Самовивіз')], default='nova_poshta', max_length=20),
        ),
    ]
