# Generated by Django 4.2.10 on 2025-02-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='total_price_gte_0',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('yookassa', 'YooKassa'), ('cash', 'Готівка')], default='cash', max_length=10),
        ),
    ]
