# Generated by Django 4.2.10 on 2025-02-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_order_total_price_gte_0_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Nova Poshta'), ('ukrposhta', 'Ukrposhta'), ('courier', 'Courier'), ('self_pickup', 'Self Pickup')], default='nova_poshta', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe-payment', 'Stripe'), ('yookassa-payment', 'Yookassa'), ('cash-on-delivery', 'Cash on Delivery')], default='cash-on-delivery', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='total_price_gte_0'),
        ),
    ]
