# Generated by Django 4.2.10 on 2025-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Nova Poshta'), ('ukrposhta', 'Ukrposhta'), ('courier', 'Courier'), ('self_pickup', 'Self Pickup')], default='nova_poshta', max_length=20),
        ),
    ]
