# Generated by Django 4.2.10 on 2025-03-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_orderitem_discount_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
