# Generated by Django 4.2.10 on 2025-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_orderitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
